import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          {/* Sidebar com Header */}
          <aside className="w-[280px] bg-white shadow-lg border-r border-gray-200 fixed h-full">
            <div className="p-6">
              <Header />
            </div>
          </aside>

          {/* Conteúdo principal - sempre à direita */}
          <main className="flex-1 ml-[280px] bg-gray-200 min-h-screen p-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
